spring:
  application:
    name: Journal App
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb+srv://prateekaga1999:IjAHfjHQEkg3DtNi@cluster0.ek2gb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  security:
    user:
      name: user
      password: password

server:
  port: 8080
  servlet:
    context-path: /journalApp

weather:
  api:
    key: a756799713fd4c6b84162443252208